CREATE USER dachsroot;
CREATE USER root;
ALTER USER dachsroot WITH SUPERUSER;
ALTER USER root WITH SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE metadata TO dachsroot;
GRANT ALL PRIVILEGES ON DATABASE metadata TO root;
