image: docker:git
services:
- docker:dind

stages:
- build

build:
  only:
    - main
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/dachs:latest dachs
    - docker push $CI_REGISTRY_IMAGE/dachs:latest
    - docker build -f postgres-metadata/Dockerfile.bitnami --build-arg POSTGRES_INIT_DIR=dachs -t $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs postgres-metadata
    - docker push $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs
    - docker build -t $CI_REGISTRY_IMAGE/rucio-datalink:latest rucio-datalink
    - docker push $CI_REGISTRY_IMAGE/rucio-datalink:latest

helm-publish:
  only:
    - main
  stage: build
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD repo https://gitlab.com/api/v4/projects/39270741/packages/helm/stable
    - helm package rucio-datalink/etc/helm
    - export CHART_NAME=`ls | grep rucio-ivoa-integrations-datalink*.tgz`
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm cm-push $CHART_NAME repo
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD repo https://gitlab.com/api/v4/projects/39270741/packages/helm/stable
    - helm package dachs/etc/helm
    - export CHART_NAME=`ls | grep rucio-ivoa-integrations-dachs*.tgz`
    - helm cm-push $CHART_NAME repo

