image: docker:git
services:
- docker:dind

stages:
- build
- helm-publish

build:
  only:
    - main
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/dachs:latest dachs
    - docker push $CI_REGISTRY_IMAGE/dachs:latest
    - docker build -f postgres-metadata/Dockerfile.bitnami --build-arg POSTGRES_INIT_DIR=dachs -t $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs postgres-metadata
    - docker push $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs

