image: docker:git
services:
- docker:dind

stages:
- build
- build-and-publish

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/

build:
  only:
    - main
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/dachs:latest dachs
    - docker push $CI_REGISTRY_IMAGE/dachs:latest
    - docker build -f postgres-metadata/Dockerfile.bitnami --build-arg POSTGRES_INIT_DIR=dachs -t $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs postgres-metadata
    - docker push $CI_REGISTRY_IMAGE/postgres-metadata:bitnami-dachs
    - docker build -t $CI_REGISTRY_IMAGE/rucio-datalink:latest rucio-datalink
    - docker push $CI_REGISTRY_IMAGE/rucio-datalink:latest

build-and-publish-dachs:
  stage: build-and-publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Dachs image"
    - echo "$CI_REGISTRY_IMAGE/dachs:$CI_COMMIT_REF_SLUG"
    - docker build -t "$CI_REGISTRY_IMAGE/dachs:$CI_COMMIT_REF_SLUG" dachs
    - echo "Pushing Dachs image to $CI_REGISTRY"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE/dachs:$CI_COMMIT_REF_SLUG"
    - echo "Successfully published Dachs image"
  only:
    - branches

build-and-publish-postgres-metadata:
  stage: build-and-publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Postgres Metadata image"
    - echo "$CI_REGISTRY_IMAGE/postgres-metadata:$CI_COMMIT_REF_SLUG"
    - docker build -f postgres-metadata/Dockerfile.bitnami --build-arg POSTGRES_INIT_DIR=dachs -t "$CI_REGISTRY_IMAGE/postgres-metadata:$CI_COMMIT_REF_SLUG" postgres-metadata
    - echo "Pushing Postgres Metadata image to $CI_REGISTRY"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE/postgres-metadata:$CI_COMMIT_REF_SLUG"
    - echo "Successfully published Postgres Metadata image"
  only:
    - branches

helm-publish:
  only:
    - main
  stage: build
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  script:
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD repo https://gitlab.com/api/v4/projects/39270741/packages/helm/stable
    - helm package rucio-datalink/etc/helm
    - export CHART_NAME=`ls | grep rucio-ivoa-integrations-datalink*.tgz`
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm cm-push $CHART_NAME repo
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD repo https://gitlab.com/api/v4/projects/39270741/packages/helm/stable
    - helm package dachs/etc/helm
    - export CHART_NAME=`ls | grep rucio-ivoa-integrations-dachs*.tgz`
    - helm cm-push $CHART_NAME repo

