version: "3.5"
services:
  dachs:
    container_name: dachs
    image: dachs
    build:
      context: ./dachs
      dockerfile: Dockerfile
    environment:
      - DACHS_POSTGRES_HOST=postgres-metadata
      - DACHS_POSTGRES_DBNAME=metadata
      - GAVORC_SERVER_URL=http://localhost:8080/
      - GAVORC_SERVER_PORT=8080
      - IVOA_AUTHORITY=test.skao
    ports:
      - 8080:8080
    networks:
      - common
  postgres:
    container_name: postgres-metadata
    image: postgres-metadata:14
    build:
      context: ./postgres-metadata
      dockerfile: Dockerfile.postgres
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=metadata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    networks:
      - common
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
  tomcat:
    container_name: tomcat-tap
    image: tomcat-tap:9
    build:
      context: ./tomcat-tap
      dockerfile: Dockerfile
      args:
       - TOMCAT_TAPSERVER_BASE_URL=/tapserver
    ports:
      - 8080:8080
    networks:
      - common
  jupyter:
    container_name: jupyter-vo
    image: jupyter-vo
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      - JUPYTER_SERVER_PASSWORD=secret
      - JUPYTER_SERVER_BASE_URL=/
    networks:
      - common
  datalink:
    container_name: rucio_datalink
    image: rucio-datalink
    build:
      context: ./rucio-datalink
      dockerfile: Dockerfile
    environment:
      - DATA_MANAGEMENT_CLIENT_ID=0ab39d2f-5428-484b-815d-dadfbad17416
      - DATA_MANAGEMENT_CLIENT_SCOPES=openid profile data-management-api-service
      - DATA_MANAGEMENT_CLIENT_AUDIENCE=data-management-api
      - DATA_MANAGEMENT_API_URL=https://data-management.srcnet.skao.int/api/v1
      - SERVICE_DATALINK_PORT=10000
      - IVOA_AUTHORITY=auth.example.org/datasets/fits
    env_file:
      - .env
    ports:
      - 10000:10000
    volumes:
      - ./rucio-datalink/src:/opt/rucio_datalink/src:rw
    networks:
      - common
networks:
  common:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.0.0/16
