version: "3.5"
services:
  dachs:
    container_name: dachs
    environment:
      - DACHS_POSTGRES_HOST=postgres-metadata
      - DACHS_POSTGRES_DBNAME=metadata
      - GAVORC_SERVER_URL=http://localhost:8080/ivoa
      - GAVORC_SERVER_PORT=8080
    ports:
      - 8080:8080
    networks:
      - common
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - 8889:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=email@email.com      
      - PGADMIN_DEFAULT_PASSWORD=secret
    networks:
      - common
    volumes:
      - ./pgadmin/etc/servers.json:/pgadmin4/servers.json
  tomcat:
    build:
      args:
       - TOMCAT_TAPSERVER_BASE_URL=/ivoa#tapserver
  jupyter:
    environment:
      - JUPYTER_SERVER_PASSWORD=secret
      - JUPYTER_SERVER_BASE_URL=/ivoa/jupyter/
