apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dachs-ingress
spec:
  rules:
  - host: ivoa.dachs.srcdev.skao.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dachs
            port:
              number: 8080
  - host: dachs.ivoa.srcdev.skao.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dachs
            port:
              number: 8080
  ingressClassName: nginx

