apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dachs 
  name: dachs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dachs
  template:
    metadata:
      labels:
        app: dachs
    spec:
      containers:
      - env:
        - name: GAVORC_SERVER_URL
          value: "{{ .Values.config.gavorc_server_url }}"
        - name: GAVORC_SERVER_PORT
          value: "{{ .Values.config.gavorc_server_port }}"
        - name: DACHS_POSTGRES_HOST
          value: "{{ .Values.config.dachs_postgres_host }}"
        - name: DACHS_POSTGRES_DBNAME
          value: "{{ .Values.config.dachs_postgres_dbname }}"
        - name: IVOA_AUTHORITY
          value: "{{ .Values.config.ivoa_authority }}"
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: dachs
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always

