apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rucio-datalink-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /rucio(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: rucio-datalink
            port:
              number: {{ .Values.service.port }}
  ingressClassName: nginx


