apiVersion: v1
kind: Service
metadata:
  labels:
    app: rucio-datalink
  name: rucio-datalink
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
  - name: "{{ .Values.service.datalink.port }}"
    port: {{ .Values.service.datalink.port }}
    targetPort: {{ .Values.service.datalink.port }} 
  selector:
    app: rucio-datalink
