apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rucio-datalink 
  name: rucio-datalink
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rucio-datalink
  template:
    metadata:
      labels:
        app: rucio-datalink
    spec:
      containers:
      - env:
        - name: DATA_MANAGEMENT_API_URL
          value: "{{ .Values.config.dataManagementApiUrl }}"
        - name: DATA_MANAGEMENT_CLIENT_SCOPES
          value: "{{ .Values.config.dataManagementClientScopes }}"
        - name: DATA_MANAGEMENT_CLIENT_AUDIENCE
          value: "{{ .Values.config.dataManagementClientAudience }}"
        - name: IVOA_AUTHORITY
          value: "{{ .Values.config.ivoaAuthority }}"
        - name: SERVICE_PORT
          value: "{{ .Values.service.port }}"
        - name: DATA_MANAGEMENT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: data-management-api-client-credentials
              key: client-id
        - name: DATA_MANAGEMENT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: data-management-api-client-credentials
              key: client-secret
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: rucio-datalink
        ports:
        - containerPort: {{ .Values.service.port }}
        resources: {}
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.service.port }}
      restartPolicy: Always
