image:
  repository: registry.gitlab.com/ska-telescope/src/src-mm/ska-src-rucio-ivoa-integrations
  name: rucio-datalink  
  tag: latest
  pullPolicy: Always

namespace: rucio-ivoa-integration

config:
  dataManagementApiEndpoint: https://data-management.srcdev.skao.int/api/v1
  dataManagementApiClientScopes: openid profile data-management-api-service
  dataManagementApiClientAudience: data-management-api
  ivoaAuthority: auth.example.org/datasets/fits

service:
  port: 8080

ingress:
  host: datalink.ivoa.srcnet.skao.int
