image:
  repository: registry.gitlab.com/ska-telescope/src/ska-rucio-ivoa-integration
  name: rucio-datalink  
  tag: latest
  pullPolicy: Always

namespace: rucio-ivoa-integration

rucioCfg:
  host: https://rucio.srcdev.skao.int
  authType: oidc
  account: root
  oidcScope: openid offline_access profile wlcg.groups
  oidcAudience: rucio https://wlcg.cern.ch/jwt/v1/any

siteCapabilitiesEndpoint: https://site-capabilities.srcdev.skao.int/api/v1
siteCapabilitiesClientId: 1f901a38-955f-4198-aedb-002332a3c551
siteCapabilitiesClientScopes: openid profile site-capabilities-api-service
siteCapabilitiesClientAudience: site-capabilities-api

ivoaAuthority: auth.example.org/datasets/fits

service:
  datalink:
    port: 8080

# Secret information, override during helm install 
oidcAgentAuthClientCfgValue: username 
oidcAgentAuthClientCfgPassword: password
siteCapabilitiesClientSecret: password


geoIpLicenseKey: secretkey
