apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youcat-temp-storage
  labels:
    app: youcat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi