# configure RegistryClient
ca.nrc.cadc.reg.client.RegistryClient.baseURL =  https://ws.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/reg

# local IVOA GMS service
ivo://ivoa.net/std/GMS#search-1.0 = ivo://cadc.nrc.ca/gms

# local OpenID service
ivo://ivoa.net/sso#OpenID = https://ska-iam.stfc.ac.uk/
