# specify implementation in case the DelegatingStorageManager is used
org.opencadc.tap.tmp.StorageManager = org.opencadc.tap.tmp.TempStorageManager

# TempStorageManager config
org.opencadc.tap.tmp.TempStorageManager.baseURL = https://localhost:9090/youcat/tmp
org.opencadc.tap.tmp.TempStorageManager.baseStorageDir = /tmp
