# tomcat-base
tomcat.connector.secure=true
tomcat.connector.scheme=http
tomcat.connector.proxyName=localhost
tomcat.connector.proxyPort=9090

# database connection pools
org.opencadc.youcat.tapadm.maxActive=5
org.opencadc.youcat.tapadm.username=postgres
org.opencadc.youcat.tapadm.password=secret
org.opencadc.youcat.tapadm.url=jdbc:postgresql://postgres-metadata:5432/metadata

org.opencadc.youcat.tapuser.maxActive=5
org.opencadc.youcat.tapuser.username=postgres
org.opencadc.youcat.tapuser.password=secret
org.opencadc.youcat.tapuser.url=jdbc:postgresql://postgres-metadata:5432/metadata

org.opencadc.youcat.uws.maxActive=5
org.opencadc.youcat.uws.username=postgres
org.opencadc.youcat.uws.password=secret
org.opencadc.youcat.uws.url=jdbc:postgresql://postgres-metadata:5432/metadata

# enable support for haproxy SSL termination + pass client cert
# ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader=false

ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager
