# (optional) configure the admin user
# for an openid service the adminUser is specified as: openid {openID service URI} {client id}
org.opencadc.youcat.adminUser = openid https://ska-iam.stfc.ac.uk/ <client ID>

# (optional) schema creation in the database (default: false)
org.opencadc.youcat.createSchemaInDB = false
