# (optional) configure the admin user
# for an openid service the adminUser is specified as: openid {openID service URI} {client id}
# org.opencadc.youcat.adminUser = openid https://ska-iam.stfc.ac.uk/ <client ID>
# org.opencadc.youcat.adminUser = openid https://ska-iam.stfc.ac.uk/ 6cc51b9d-5a19-5716-95d0-dfb32d65a4h2

# (optional) schema creation in the database (default: false)
org.opencadc.youcat.createSchemaInDB = false
